import Head from "next/head"
import Image from "next/image"
import connectMongo from "../../database/connectMongo"
import Test from "../../database/models/test"

export default function Home({ tests }) {
  const createTest = async () => {
    const randomNum = Math.floor(Math.random() * 1000)
    const res = await fetch("/api/test/add", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: `Test ${randomNum}`,
        email: `test${randomNum}@test.com`,
      }),
    })
    const data = await res.json()
    console.log(`From Client Api Post ${data}`)
  }
  return (
    <div className={``}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <button className={`px-4 py-2 bg-blue-200`} onClick={createTest}>
          Create Test
        </button>

        <div className={``}>
          {tests.map((test) => (
            <a href="https://nextjs.org/docs" key={`${test?._id}`} className="">
              <h2>{test?.name} &rarr;</h2>
              <p>{test?.email}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={``}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={``}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  try {
    console.log("CONNECTING TO MONGO")
    await connectMongo()
    console.log("CONNECTED TO MONGO")

    console.log("FETCHING DOCUMENTS")
    const tests = await Test.find()
    console.log("FETCHED DOCUMENTS")

    return {
      props: {
        tests: JSON.parse(JSON.stringify(tests)),
      },
    }
  } catch (error) {
    console.log(error)
    return {
      notFound: true,
    }
  }
}
